[workspace]
members = [
    "blindwire-cli",
    "blindwire-core",
    "blindwire-server",
    "blindwire-transport",
]
resolver = "2"

[profile.release]
# Maximize reproducibility and optimization
codegen-units = 1
lto = true
panic = "abort"
strip = true
opt-level = 3

